### ISSUE TITLE
Documentation: "Integration with Embeddable"

### ISSUE THREAD

**Issue by eugeneoshepkov** [questdb/documentation#18]
We'd like to add "Embeddable" integration with QuestDB to "Third-party tools" section of your documentation. 

Here's the gist with the markdown for it: https://gist.github.com/eugeneoshepkov/45d105f567c7daa8e38e645cadf675c1

There we described the process of integrating QuestDB with Embeddable. 

Thank you

**Comment by goodroot** [comment]
Hey @eugeneoshepkov, thanks - the PR is in progress, and near complete.

Quick question - there are links to cube.dev docs. 

We provide Cube as a tool as well.

Is this link incorrect?

```
The `name` is a unique name to identify this **connection**.

- By default your **data models** will look for a **connection** called
  “default”, but you can supply your models with different
  [**data_source**](https://cube.dev/docs/reference/data-model/cube#data_source)
  names to support connecting different **data models** to different
  **connections** (simply specify the
  **[data_source](https://cube.dev/docs/reference/data-model/cube#data_source)**
  name in the model)

The `type` tells us which driver to use, in this case QuestDB. For a full list,
see
[the documentaiton](https://cube.dev/docs/product/configuration/data-sources).
```

**Comment by eugeneoshepkov** [comment]
@goodroot Yes this is correct, we rely on Cube and mention it in our docs: https://www.notion.so/trevorio/Connections-API-ff4af10f7eaf4288b6952fde04e6e933

**Comment by eugeneoshepkov** [comment]
@goodroot Could you please take the latest gist to your PR? I've just updated some text there

**Comment by goodroot** [comment]
@eugeneoshepkov Live! Feel free to open a PR to make any future alterations.


https://questdb.io/docs/third-party-tools/embeddable/
