### ISSUE TITLE
Wrong naming of INTEGER vs. INT

### ISSUE THREAD

**Issue by juocal** [questdb/documentation#54]
Hey there,

I possibly found a issue regarding the naming of data types. 

You are using `INTEGER` in this example in the documentation:
https://questdb.io/docs/reference/sql/alter-table-change-column-type/#examples

It should be `INT` as there is no `INTEGER` type (anymore?)

Change from:
```
ALTER TABLE employees ALTER COLUMN age TYPE INTEGER;
```

to:
```
ALTER TABLE employees ALTER COLUMN age TYPE INT;
```

Also in the text, there is the mention of `INTEGER`.
This issue should be used to find other occurances of INTEGER in the documentation, as there might be other examples where `INTEGER` is used instead of `INT`

**Comment by Xtha-Sunil** [comment]
I will like to work on this. Could you please assign this to me.
